w7d3/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new,:create,:destroy]
  resources :bands
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, only: [:create,:edit,:show,:update,:destroy]
end

w7d3/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title,:year,:band_id,presence:true
  validates :live, inclusion: {in: [true,false]}      #special validation for boolean
end

w7d3/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence:true
end

w7d3/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email,:password_digest,:session_token,presence:true
  validates :email,:session_token,uniqueness:true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token
  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email,password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    password_object = BCrypt::Password.new(self.password_digest)
    password_object.is_password?(password)
  end
end

w7d3/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save!                  
      redirect_to album_url(@album)
    else
      redirect_to :new
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      redirect_to albums_url
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  def album_params
    params.require(:album).permit(:title,:year,:band_id,:live)
  end
end

w7d3/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user,:logged_in?
  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end
end

w7d3/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      redirect_to :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      redirect_to bands_url
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

w7d3/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
      current_user.reset_session_token!
      session[:session_token] = nil
      @current_user = nil
      redirect_to new_session_url
  end
end

w7d3/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      redirect_to :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  def user_params
    params.require(:user).permit(:email,:password)
  end


end

w7d3/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

w7d3/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
        "<input type = 'hidden' name = 'authenticity_token' value = '#{form_authenticity_token}'/>".html_safe
    end
end

w7d3/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

w7d3/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

w7d3/music_app/app/helpers/users_helper.rb
module UsersHelper
end

w7d3/music_app/app/views/bands/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Update Band</h1>
     <form action="<%= band_url(@band) %>" method = "POST">
     <%= auth_token %>
     <input type="hidden" name="_method" value="PATCH">
      <label for="Name">Name
        <input type="text" id = "Name" name = "band[name]" value = "<%= @band.name %>">
      </label>
      <input type="submit" value="Update Band">
     </form>
  </body>
</html>

w7d3/music_app/app/views/bands/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% @bands.each do |band| %>
    <br>
     <a href="<%= band_url(band) %>"><%= band.id %>.<%= band.name %></a>
    <% end %>
  </body>
</html>

w7d3/music_app/app/views/bands/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Create Band</h1>
     <form action="<%= bands_url %>" method = "POST">
     <%= auth_token %>
      <label for="Name">Name
        <input type="text" id = "Name" name = "band[name]">
      </label>
      <input type="submit" value="Create Band">
     </form>
  </body>
</html>

w7d3/music_app/app/views/bands/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <h1>Hello, <%= @band.name %></h1>
  </body>
</html>

w7d3/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>Music App</header>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
      <%= auth_token %>
        <input type="hidden" name = "_method" value="delete">
        <input type="submit" value="Sign-out">
      </form>
    <h2>Current User: <%= current_user.email %></h2>
    <% else %>
      <a href="<%= new_session_url %>">Login</a>
      <a href="<%= new_user_url %>">Signup</a>
    <% end %>
    <%= yield %>
  </body>
</html>

w7d3/music_app/app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% @users.each do |user| %>
    <br>
     <a href="<%= user_url(user) %>"><%= user.email %></a>
    <% end %>
  </body>
</html>

w7d3/music_app/app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Create User Account</h1>
  <%= auth_token %>
     <form action="<%= users_url %>" method = "POST">
      <label for="Email">Email
        <input type="text" id = "Email" name = "user[email]">
      </label>
      <label for="Password">Password
        <input type="text" id = "Password" name = "user[password]">
      </label>
      <input type="submit" value="Create User">
     </form>
  </body>
</html>

w7d3/music_app/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <h1>Hello, <%= @user.email %></h1>
  </body>
</html>